### ISSUE TITLE
Is this project still living?

### ISSUE THREAD

**Issue by fish1968** [bytedance/kernel#1]
Looking at the last modified time in front page of your project's mian branch, I find most haven't been updated since 10 months ago.  
Also, far as I could see, the READEME file is merely a copy from linux kernel. There's no explicit guide for user to know more about your kernel project, like the features of your kernel, how a user could make use of the project, etc.  
I am looking forward to some hint about using your kernel (compile, installing,...) .  
Please🤔 
Hope to see some reply soon.

**Comment by Hunter1016** [comment]
> Looking at the last modified time in front page of your project's mian branch, I find most haven't been updated since 10 months ago. Also, far as I could see, the READEME file is merely a copy from linux kernel. There's no explicit guide for user to know more about your kernel project, like the features of your kernel, how a user could make use of the project, etc. I am looking forward to some hint about using your kernel (compile, installing,...) . Please🤔 Hope to see some reply soon.

Sorry for late reply, this repo is ByteDance maintained kernel for use on cloud, and of course it's in rapid iteration. The branches and tags correspond to kernel releases available on veLinux, which is the native OS on volcengine cloud platform (https://www.volcengine.com/about).
For making use of this project, it can be easily achieved by launching an ECS instance on https://www.volcengine.com/product/ecs and choose veLinux as your OS image. Or you can follow kernel guidelines, just make && make install.
For more details, please refer to this page https://bytedance.github.io/kernel/.
